@startuml
package Engine{
package Model{
    package "Sequential Model" {

    }
    package "Functional API" {
        
    }
}
package Layer{
    package "Dense Layer" {

    }
    package "Recurrent Layer" {

    }
    package "Convolution Layer"{

    } 
    package "Dropout Layer"{

    } 
    package "Pooling Layer"{

    } 
}
}
package "Keras Modules" {
    package Activations {

    }
    package Losses {

    }
    package Optimizers {

    }
    package Regularizers{

    }
    package Initializers{

    }
}
Layer <.right. Model: composed of
Engine .down.> "Keras Modules"

@enduml