@startuml
title Keras - Layered Architecture
package "Keras Cores"{
package Engine{
    package Model {
    package "Sequential Model" <<Folder>>{

    }
    package "Functional API" <<Folder>>{
        
    }
    }

    package "Base Layer" <<Folder>>{

    }
}
package Layers{
    package "Core Layer" <<Folder>>{

    }
    package "Recurrent Layer" <<Folder>>{

    }
    package "Convolution Layer" <<Folder>>{

    } 
    package "Pooling Layer" <<Folder>>{

    } 
}
}
package "Keras Modules" {
    package Activations <<Folder>>{

    }
    package Losses <<Folder>>{

    }
    package Optimizers <<Folder>>{

    }
    package Regularizers <<Folder>>{

    }
    package Initializers <<Folder>>{

    }
    package Metrics <<Folder>>{

    }
}
"Base Layer" <.left. Model: <<import>>
Layers .right.> "Base Layer" :<<import>>
"Keras Cores" .down.> "Keras Modules": <<import>>
"Sequential Model" .right.> "Functional API" :<<import>>
"Pooling Layer" <.left. "Convolution Layer" :<<import>>
 Activations <.left. Metrics:<<import>>
Metrics .right.> Losses:<<import>>
Initializers <.left. Optimizers: <<import>>
@enduml