@startuml
title Keras- Layered Architecture
package "Keras Cores"{
package Engine{
    package "Sequential Model" <<Folder>>{

    }
    package "Functional API" <<Folder>>{
        
    }
}
package Layers{
    package "Core Layer" <<Folder>>{

    }
    package "Recurrent Layer" <<Folder>>{

    }
    package "Convolution Layer" <<Folder>>{

    } 
    package "Pooling Layer" <<Folder>>{

    } 
}
}
package "Keras Modules" {
    package Activations <<Folder>>{

    }
    package Losses <<Folder>>{

    }
    package Optimizers <<Folder>>{

    }
    package Regularizers <<Folder>>{

    }
    package Initializers <<Folder>>{

    }
    package Metrics <<Folder>>{

    }
}
Layers <.right. Engine: use
"Keras Cores" .down.> "Keras Modules": use
"Sequential Model" .right.> "Functional API" :use

@enduml